name: blog
dependencies:
  - python=3.5
  - jupyter=1.0
  - numpy
  - pymc
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - pip:
    - Markdown==2.6.6
    - pelican==3.6.3
    - nbconvert==4.0
      #    - ghp-import==0.4.1
    - pelican-gist==0.3.3
      #- disquis-python==0.4.2
    - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl
